apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api
  labels:
    app: bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: bank-api
        image: 192.168.1.27/java-bank-api/bank-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/postgres"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "postgres"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=java-bank-api"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://simplest-collector.default.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"

---
apiVersion: v1
kind: Service
metadata:
  name: bank-api
  labels:
    app: bank-api
spec:
  type: NodePort
  ports:
  - port: 8080  # Container'daki port
    targetPort: 8080  # Uygulamanın dinlediği port
    nodePort: 30080  # Dış dünyaya açılan port
  selector:
    app: bank-api